### ISSUE TITLE
UnhandledPromiseRejectionWarning in logs

### ISSUE THREAD

**Issue by ekobres** [grivkees/homebridge-carrier-infinity#1]
I installed the new update with zone support and saw these exceptions in the logs. 

HomeKit accessories only showed one thermostat - this is a 2 zone system.

> INFO: SmartThings-v2 Hub Communication Established
(node:10346) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toString' of undefined
    at InfinityEvolutionSystemConfig.getZone (/usr/local/lib/node_modules/homebridge-carrier-infinity/src/infinityApi.ts:323:55)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at InfinityEvolutionSystemConfig.getZoneName (/usr/local/lib/node_modules/homebridge-carrier-infinity/src/infinityApi.ts:327:22)
    at /usr/local/lib/node_modules/homebridge-carrier-infinity/src/platformAccessory.ts:36:73
(Use `node --trace-warnings ...` to show where the warning was created)
(node:10346) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:10346) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:10346) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toString' of undefined
    at InfinityEvolutionSystemConfig.getZone (/usr/local/lib/node_modules/homebridge-carrier-infinity/src/infinityApi.ts:323:55)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at InfinityEvolutionSystemConfig.getZoneName (/usr/local/lib/node_modules/homebridge-carrier-infinity/src/infinityApi.ts:327:22)
    at /usr/local/lib/node_modules/homebridge-carrier-infinity/src/platformAccessory.ts:36:73
(node:10346) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[21/05/2021, 05:13:57] [homebridge-carrier-infinity] This plugin threw an error from the characteristic 'Current Temperature': Unhandled error thrown inside read handler for characteristic: Cannot read property 'rt' of undefined. See https://git.io/JtMGR for more info.
[21/05/2021, 05:13:57] [homebridge-carrier-infinity] TypeError: Cannot read property 'rt' of undefined
    at InfinityEvolutionSystemStatus.getZoneTemp (/usr/local/lib/node_modules/homebridge-carrier-infinity/src/infinityApi.ts:274:46)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at CurrentTemperature.getHandler (/usr/local/lib/node_modules/homebridge-carrier-infinity/src/platformAccessory.ts:108:54)
[21/05/2021, 05:13:57] [homebridge-carrier-infinity] This plugin threw an error from the characteristic 'Current Relative Humidity': Unhandled error thrown inside read handler for characteristic: Cannot read property 'rh' of undefined. See https://git.io/JtMGR for more info.
[21/05/2021, 05:13:57] [homebridge-carrier-infinity] TypeError: Cannot read property 'rh' of undefined
    at InfinityEvolutionSystemStatus.getZoneHumidity (/usr/local/lib/node_modules/homebridge-carrier-infinity/src/infinityApi.ts:278:46)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at CurrentRelativeHumidity.getHandler (/usr/local/lib/node_modules/homebridge-carrier-infinity/src/platformAccessory.ts:194:16)
[21/05/2021, 05:13:57] [homebridge-carrier-infinity] This plugin threw an error from the characteristic 'Cooling Threshold Temperature': Unhandled error thrown inside read handler for characteristic: Cannot read property 'toString' of undefined. See https://git.io/JtMGR for more info.
[21/05/2021, 05:13:57] [homebridge-carrier-infinity] TypeError: Cannot read property 'toString' of undefined
    at InfinityEvolutionSystemConfig.getZone (/usr/local/lib/node_modules/homebridge-carrier-infinity/src/infinityApi.ts:323:55)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at InfinityEvolutionSystemConfig.getZoneActivity (/usr/local/lib/node_modules/homebridge-carrier-infinity/src/infinityApi.ts:335:22)
    at InfinityEvolutionPlatformAccessory.getZoneActvity (/usr/local/lib/node_modules/homebridge-carrier-infinity/src/platformAccessory.ts:201:12)
    at CoolingThresholdTemperature.getHandler (/usr/local/lib/node_modules/homebridge-carrier-infinity/src/platformAccessory.ts:151:13)
[21/05/2021, 05:13:57] [homebridge-carrier-infinity] This plugin threw an error from the characteristic 'Heating Threshold Temperature': Unhandled error thrown inside read handler for characteristic: Cannot read property 'toString' of undefined. See https://git.io/JtMGR for more info.
[21/05/2021, 05:13:57] [homebridge-carrier-infinity] TypeError: Cannot read property 'toString' of undefined
    at InfinityEvolutionSystemConfig.getZone (/usr/local/lib/node_modules/homebridge-carrier-infinity/src/infinityApi.ts:323:55)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at InfinityEvolutionSystemConfig.getZoneActivity (/usr/local/lib/node_modules/homebridge-carrier-infinity/src/infinityApi.ts:335:22)
    at InfinityEvolutionPlatformAccessory.getZoneActvity (/usr/local/lib/node_modules/homebridge-carrier-infinity/src/platformAccessory.ts:201:12)
    at HeatingThresholdTemperature.getHandler (/usr/local/lib/node_modules/homebridge-carrier-infinity/src/platformAccessory.ts:174:13)
[21/05/2021, 05:13:57] [homebridge-carrier-infinity] This plugin threw an error from the characteristic 'Target Temperature': Unhandled error thrown inside read handler for characteristic: Cannot read property 'toString' of undefined. See https://git.io/JtMGR for more info.
[21/05/2021, 05:13:57] [homebridge-carrier-infinity] TypeError: Cannot read property 'toString' of undefined
    at InfinityEvolutionSystemConfig.getZone (/usr/local/lib/node_modules/homebridge-carrier-infinity/src/infinityApi.ts:323:55)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at InfinityEvolutionSystemConfig.getZoneActivity (/usr/local/lib/node_modules/homebridge-carrier-infinity/src/infinityApi.ts:335:22)
    at InfinityEvolutionPlatformAccessory.getZoneActvity (/usr/local/lib/node_modules/homebridge-carrier-infinity/src/platformAccessory.ts:201:12)
    at TargetTemperature.getHandler (/usr/local/lib/node_modules/homebridge-carrier-infinity/src/platformAccessory.ts:114:26)
[21/05/2021, 05:14:03] [homebridge-carrier-infinity] This plugin threw an error from the characteristic 'Current Temperature': Unhandled error thrown inside read handler for characteristic: Cannot read property 'rt' of undefined. See https://git.io/JtMGR for more info.
[21/05/2021, 05:14:03] [homebridge-carrier-infinity] TypeError: Cannot read property 'rt' of undefined
    at InfinityEvolutionSystemStatus.getZoneTemp (/usr/local/lib/node_modules/homebridge-carrier-infinity/src/infinityApi.ts:274:46)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at CurrentTemperature.getHandler (/usr/local/lib/node_modules/homebridge-carrier-infinity/src/platformAccessory.ts:108:54)
[21/05/2021, 05:14:03] [homebridge-carrier-infinity] This plugin threw an error from the characteristic 'Current Relative Humidity': Unhandled error thrown inside read handler for characteristic: Cannot read property 'rh' of undefined. See https://git.io/JtMGR for more info.
[21/05/2021, 05:14:03] [homebridge-carrier-infinity] TypeError: Cannot read property 'rh' of undefined
    at InfinityEvolutionSystemStatus.getZoneHumidity (/usr/local/lib/node_modules/homebridge-carrier-infinity/src/infinityApi.ts:278:46)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at CurrentRelativeHumidity.getHandler (/usr/local/lib/node_modules/homebridge-carrier-infinity/src/platformAccessory.ts:194:16)
[21/05/2021, 05:14:03] [homebridge-carrier-infinity] This plugin threw an error from the characteristic 'Cooling Threshold Temperature': Unhandled error thrown inside read handler for characteristic: Cannot read property 'toString' of undefined. See https://git.io/JtMGR for more info.
[21/05/2021, 05:14:03] [homebridge-carrier-infinity] TypeError: Cannot read property 'toString' of undefined
    at InfinityEvolutionSystemConfig.getZone (/usr/local/lib/node_modules/homebridge-carrier-infinity/src/infinityApi.ts:323:55)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at InfinityEvolutionSystemConfig.getZoneActivity (/usr/local/lib/node_modules/homebridge-carrier-infinity/src/infinityApi.ts:335:22)
    at InfinityEvolutionPlatformAccessory.getZoneActvity (/usr/local/lib/node_modules/homebridge-carrier-infinity/src/platformAccessory.ts:201:12)
    at CoolingThresholdTemperature.getHandler (/usr/local/lib/node_modules/homebridge-carrier-infinity/src/platformAccessory.ts:151:13)
[21/05/2021, 05:14:03] [homebridge-carrier-infinity] This plugin threw an error from the characteristic 'Heating Threshold Temperature': Unhandled error thrown inside read handler for characteristic: Cannot read property 'toString' of undefined. See https://git.io/JtMGR for more info.
[21/05/2021, 05:14:03] [homebridge-carrier-infinity] TypeError: Cannot read property 'toString' of undefined
    at InfinityEvolutionSystemConfig.getZone (/usr/local/lib/node_modules/homebridge-carrier-infinity/src/infinityApi.ts:323:55)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at InfinityEvolutionSystemConfig.getZoneActivity (/usr/local/lib/node_modules/homebridge-carrier-infinity/src/infinityApi.ts:335:22)
    at InfinityEvolutionPlatformAccessory.getZoneActvity (/usr/local/lib/node_modules/homebridge-carrier-infinity/src/platformAccessory.ts:201:12)
    at HeatingThresholdTemperature.getHandler (/usr/local/lib/node_modules/homebridge-carrier-infinity/src/platformAccessory.ts:174:13)
[21/05/2021, 05:14:03] [homebridge-carrier-infinity] This plugin threw an error from the characteristic 'Target Temperature': Unhandled error thrown inside read handler for characteristic: Cannot read property 'toString' of undefined. See https://git.io/JtMGR for more info.
[21/05/2021, 05:14:03] [homebridge-carrier-infinity] TypeError: Cannot read property 'toString' of undefined
    at InfinityEvolutionSystemConfig.getZone (/usr/local/lib/node_modules/homebridge-carrier-infinity/src/infinityApi.ts:323:55)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at InfinityEvolutionSystemConfig.getZoneActivity (/usr/local/lib/node_modules/homebridge-carrier-infinity/src/infinityApi.ts:335:22)
    at InfinityEvolutionPlatformAccessory.getZoneActvity (/usr/local/lib/node_modules/homebridge-carrier-infinity/src/platformAccessory.ts:201:12)
    at TargetTemperature.getHandler (/usr/local/lib/node_modules/homebridge-carrier-infinity/src/platformAccessory.ts:114:26)

**Comment by grivkees** [comment]
Should be fixed by https://github.com/grivkees/homebridge-carrier-infinity/commit/564f32b1a460227c5e7f1c09996e9ec25770008c.

Building new version now and pushing.
